Repository book-hub-umsp/book-hub-api, pull requests merged in 2024-12, with the labels that each got.

#129 Updatind previus version meta
  .github/workflows/deploy.yml
Labels: patch

#130 Update deploy.yml
  .github/workflows/deploy.yml
Labels: patch

#131 update cmd
  .github/workflows/deploy.yml
Labels: patch

#132 fix deploy job again
  .github/workflows/deploy.yml
Labels: patch

#133 Update deploy.yml
  .github/workflows/deploy.yml
Labels: patch

#134 Update deploy.yml
  .github/workflows/deploy.yml
Labels: patch

#135 Add missing options for extract version job
  .github/workflows/deploy.yml
Labels: patch

#136 Update deploy.yml
  .github/workflows/deploy.yml
Labels: patch

#137 Update deploy.yml
  .github/workflows/deploy.yml
Labels: patch

#127 #28 refactor user favorites logic. add api for user favorites
  BookHub.API/Controllers/BookDescriptionController.cs
  BookHub.API/Controllers/FavoritesController.cs
  BookHub.Abstractions/Logic/Services/Favorite/IUserFavoriteService.cs
  BookHub.Abstractions/Storage/Repositories/IBooksRepository.cs
  BookHub.Abstractions/Storage/Repositories/IFavoriteLinkRepository.cs
  BookHub.Contracts/REST/Responses/Books/Repository/BookPreview.cs
  BookHub.Logic/Services/Favorite/UserFavoriteService.cs
  BookHub.Models.Tests/Favorite/UsersFavorite.Tests.cs
  BookHub.Models/Favorite/UsersFavorite.cs
  BookHub.Storage/PostgreSQL/Models/Previews/StorageBookPreview.cs
  BookHub.Storage/PostgreSQL/Models/Previews/StorageChapterPreview.cs
  BookHub.Storage/PostgreSQL/QueryExtensions.cs
  BookHub.Storage/PostgreSQL/Repositories/BooksRepository.Expressions.cs
  BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
  BookHub.Storage/PostgreSQL/Repositories/FavoriteLinkRepository.cs
Labels: minor

#139 feature/#81 Валидация подписи Google и Yandex
  BookHub.API/Authentification/Configuration/JWT/AuthConfigurationValidator.cs
  BookHub.API/Authentification/Configuration/JWT/ProviderConfigurationBase.cs
  BookHub.API/Authentification/YandexAuthService.cs
  BookHub.API/Controllers/ChaptersController.cs
  BookHub.API/Program.cs
  BookHub.API/Registrations/AuthentificationExtensions.cs
  BookHub.API/appsettings.json
  BookHub.Abstractions/BookHub.Abstractions.csproj
  BookHub.Abstractions/Logic/Services/Auth/IYandexAuthService.cs
Labels: minor

#141 d
  BookHub.API/appsettings.json
Labels: patch

#142 fix registering
  BookHub.API/Controllers/UserController.cs
Labels: patch

#146 Feature/#145 fix repositories
  BookHub.API/Controllers/BookDescriptionController.cs
  BookHub.API/Controllers/BooksGenresController.cs
  BookHub.API/Controllers/ChaptersController.cs
  BookHub.API/Controllers/FavoritesController.cs
  BookHub.API/Controllers/UserController.cs
  BookHub.Abstractions/Logic/Services/Books/Repository/IBookDescriptionService.cs
  BookHub.Abstractions/Storage/Repositories/IBooksRepository.cs
  BookHub.Contracts/REST/Requests/Books/Repository/AddAuthorBookParams.cs
  BookHub.Contracts/REST/Requests/Books/Repository/AddBookParams.cs
  BookHub.Contracts/REST/Requests/Books/Repository/UpdateBookParams.cs
  BookHub.Logic/Converters/Books/Repository/BookParamsConverter.cs
  BookHub.Logic/Services/Books/Repository/BookDescriptionService.cs
  BookHub.Logic/Services/Books/Repository/BookGenresService.cs
  BookHub.Logic/Services/Favorite/UserFavoriteService.cs
  BookHub.Models/Books/Repository/BookAnnotation.cs
  BookHub.Models/CRUDS/Requests/AddAuthorBookParams.cs
  BookHub.Models/CRUDS/Requests/AddBookParams.cs
  BookHub.Models/CRUDS/Requests/ExtendKeyWordsParams.cs
  BookHub.Models/CRUDS/Requests/UpdateBookAnnotationParams.cs
  BookHub.Models/CRUDS/Requests/UpdateBookGenreParams.cs
  BookHub.Models/CRUDS/Requests/UpdateBookParamsBase.cs
  BookHub.Models/CRUDS/Requests/UpdateBookStatusParams.cs
  BookHub.Models/CRUDS/Requests/UpdateBookTitleParams.cs
  BookHub.Storage/PostgreSQL/BooksHubContext.cs
  BookHub.Storage/PostgreSQL/Models/Book.cs
  BookHub.Storage/PostgreSQL/Models/User.cs
  BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
  BookHub.Storage/PostgreSQL/Repositories/FavoriteLinkRepository.cs
Labels: bug
