Repository book-hub-umsp/book-hub-api, pull requests merged in 2024-10, with the labels that each got.

#11 fix action problem #9
  .github/workflows/build-docker.yml
  .github/workflows/test-dotnet.yml
  BooksService.sln
  src/docker-compose.dcproj
  src/docker-compose.override.yml
  src/docker-compose.yml
Labels: devops

#34 Feature/#33 add test auth
  .editorconfig
  BookHub.API/Authentification/CustomAuthorizationHandler.cs
  BookHub.API/Authentification/CustomRequirementMarker.cs
  BookHub.API/BookHub.API.csproj
  BookHub.API/Controllers/BaseController.cs
  BookHub.API/Controllers/TestAuthController.cs
  BookHub.API/Program.cs
Labels: patch

#32 Add books storage 22
  BookHub.API/BookHub.API.csproj
  BookHub.API/Program.cs
  BookHub.API/Registrations/StorageExtensions.cs
  BookHub.API/appsettings.json
  BookHub.Contracts/BookHub.Contracts.csproj
  BookHub.Contracts/KeyWord.cs
  BookHub.Contracts/KeyWordsContainer.cs
  BookHub.Models/Books/BookDescription.cs
  BookHub.Models/Books/BookGenre.cs
  BookHub.Models/Books/KeyWord.cs
  BookHub.Storage/BookHub.Storage.csproj
  BookHub.Storage/PostgreSQL/Abstractions/IBooksUnitOfWork.cs
  BookHub.Storage/PostgreSQL/Abstractions/IKeyWordsConverter.cs
  BookHub.Storage/PostgreSQL/Abstractions/IRepositoryContext.cs
  BookHub.Storage/PostgreSQL/Abstractions/IUnitOfWork.cs
  BookHub.Storage/PostgreSQL/Abstractions/Repositories/IBooksRepository.cs
  BookHub.Storage/PostgreSQL/BooksContext.cs
  BookHub.Storage/PostgreSQL/BooksUnitOfWork.cs
  BookHub.Storage/PostgreSQL/KeyWordsConverter.cs
  BookHub.Storage/PostgreSQL/Models/Book.cs
  BookHub.Storage/PostgreSQL/Models/BookGenre.cs
  BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
  BookHub.Storage/PostgreSQL/Repositories/RepositoryBase.cs
  BookHub.Storage/PostgreSQL/RepositoryContext.cs
  BookHub.sln
  Migrations/0_init_db.sql
  Migrations/1_create_book.sql
Labels: patch

#36 Feature/#23 book fav models
  BookHub.Models.Tests/UserFavoriteBookLink.Tests.cs
  BookHub.Models.Tests/UsersFavorite.Tests.cs
  BookHub.Models/UserFavoriteBookLink.cs
  BookHub.Models/UsersFavorite.cs
Labels: minor

#39 #39 add test config
  BookHub.API/Controllers/TestAuthController.cs
  BookHub.API/Program.cs
  BookHub.API/TestConfig.cs
  BookHub.API/TestConfigValidator.cs
  BookHub.API/appsettings.json
Labels: patch

#37 Feaure/#19 add user storage
  BookHub.API/Registrations/StorageExtensions.cs
  BookHub.Abstractions/BookHub.Abstractions.csproj
  BookHub.Abstractions/IBooksHubUnitOfWork.cs
  BookHub.Abstractions/Repositories/IBooksRepository.cs
  BookHub.Abstractions/Repositories/IUsersRepository.cs
  BookHub.Models.Tests/Users/User.Tests.cs
  BookHub.Models/DomainEvents/UpdatedBase.cs
  BookHub.Models/DomainEvents/Users/Updated{TAttribute}.cs
  BookHub.Models/Users/RegisteringUser.cs
  BookHub.Models/Users/User.cs
  BookHub.Models/Users/UserPermission.cs
  BookHub.Storage/BookHub.Storage.csproj
  BookHub.Storage/PostgreSQL/Abstractions/IRepositoryContext.cs
  BookHub.Storage/PostgreSQL/BooksHubContext.cs
  BookHub.Storage/PostgreSQL/BooksHubUnitOfWork.cs
  BookHub.Storage/PostgreSQL/KeyWordsConverter.cs
  BookHub.Storage/PostgreSQL/Models/User.cs
  BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
  BookHub.Storage/PostgreSQL/Repositories/UsersRepository.cs
  BookHub.Storage/PostgreSQL/RepositoryContext.cs
  BookHub.sln
  Migrations/000_init_db.sql
  Migrations/001_create_book.sql
  Migrations/002_create_user.sql
Labels: minor
